### ISSUE TITLE
windows icon and title

### ISSUE THREAD

**Issue by davidjtferguson** [davidjtferguson/silly-sam#31]
Currently the icon in the top right corner is the love2d icon, and the title says 'Untitled'.

Can change the icon using 
```
imageData = love.image.newImageData( "filename.png" )
success = love.window.setIcon( imageData )
```
Need a 32x32 image to become the windows icon.

and can change the title using
```
love.window.setTitle( "Silly Sam" )
```

**Comment by davidjtferguson** [comment]
I've just added a placeholder image to see how it loads and added the title. Leaving this open until one of the artists supplies an image that replaces the placeholder.

**Comment by rcsweeney** [comment]
replaced old window_icon with my own. lemme know if you need anything else for this

**Comment by davidjtferguson** [comment]
Reopening since the windows icon is still the old sam art.
