### ISSUE TITLE
Grabby Hands!

### ISSUE THREAD

**Issue by rcsweeney** [davidjtferguson/silly-sam#39]
Once analogue-trigger-legs are in and we're happy with how they feel - can use LB and RB to make the hands grab! If too difficult codewise just gimmi a slap and leave it. But if simple, I think it could be hilarious to awkwardly jump and dangle off things by grabbing on to them. (think of a flying fox, moving platform, a lever you have to pull, a rope you have to pull to play tug-of-war, or being able to hold items).

how I imagine the logic working: radius around hands that's slightly larger than an open hand - and some objects are marked either grabbable and they stay stationary, or grabbable and they can be picked up. or I guess if it's all physics it would just depend on the weight of the object. don't need a magnet-hand system to snap the object close, a visual gap is totally fine I feel *in the case we grab on to something at the edge of the radius, and the closed hand sprite is smaller than this

**Comment by davidjtferguson** [comment]
completed in PR #47
