### ISSUE TITLE
Animate backgrounds technique

### ISSUE THREAD

**Issue by davidjtferguson** [davidjtferguson/silly-sam#50]
Thinking of the best way to have backgrounds with a little movement.

One option is to have groups of bodies on a different 'layer' than the game layer then have some persistive force against them (say, wind force against trees) so they have constent movement.
A stretch goal of this idea would be to have sam 'influence' these objects as he moves past them.
Advantages: Would be consistent with the animation style of sam hiself and would create dynamic animation.
Disadvantages: Moves more work to code side, would be a fair bit of work to make a model in Tiled so people can create their own things iin the system. Too many bodies may start to invite slowdown, though I'm not sure where our boundries lie with this.

Other option is to have spritesheets for each of these things.
Advantages and disadvantages are basically opposite - would be implmementing a different animation style for a different layer which might be jaring (Although maybe the seperation of styles would be good for communicating to the user what is interactable or not?) and would move work to the art side instead of the code. Would be easier to put into the map.

Static backgrounds should be put in first before exploring these options I think.

**Comment by rcsweeney** [comment]
issue closed, not implementing animated background objects
