### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by davidjtferguson** [davidjtferguson/silly-sam#59]
A Silly Sam logo to put in the sky for the first screen as the game starts, for some kind of 'intro' to welcome the player.

Similar to how Rolly welcomed the player with the Rolly logo flying in the air when first entering the hub.

**Comment by richardbmx** [comment]
@davidjtferguson  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by davidjtferguson** [comment]
Hey Richard - thanks for getting in touch that's cool that you do that but we aren't looking for extra help I'm afraid.
