### ISSUE TITLE
Store picture card for Itch.io

### ISSUE THREAD

**Issue by davidjtferguson** [davidjtferguson/silly-sam#60]
If you look at the itch.io front page, each game has an image associated with it to entice the player to try it out:
https://itch.io/

Need one of these for sam - preferably containing the logo discussed in issue #59 .

**Comment by rcsweeney** [comment]
updated and fixed the white ball artifact

**Comment by davidjtferguson** [comment]
Re-opening as this will need to be re-done for the new art pass
